services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guest"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    user: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  healthy:
    image: alpine
    command: echo "All services started and healthy!"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy